// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs5zb8V_5oQSsySfVyDYKOQVs8noMKLoI',
    appId: '1:632269329403:web:bf7228726dfd8de3b8f15e',
    messagingSenderId: '632269329403',
    projectId: 'flutter-bt-firebase',
    authDomain: 'flutter-bt-firebase.firebaseapp.com',
    storageBucket: 'flutter-bt-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiaXkYzlj3JSDZUXtoaL5uIkUYArVIJsU',
    appId: '1:632269329403:android:64404e1c40e2a348b8f15e',
    messagingSenderId: '632269329403',
    projectId: 'flutter-bt-firebase',
    storageBucket: 'flutter-bt-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvdNHNGxDp_KFGYbZH6CrWt0BW8T4eSFQ',
    appId: '1:632269329403:ios:9900540ac6d2bc02b8f15e',
    messagingSenderId: '632269329403',
    projectId: 'flutter-bt-firebase',
    storageBucket: 'flutter-bt-firebase.appspot.com',
    iosClientId: '632269329403-de8se93qvdti4oiiu9jlmum14d9vplja.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcampApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvdNHNGxDp_KFGYbZH6CrWt0BW8T4eSFQ',
    appId: '1:632269329403:ios:0d13671e054454d8b8f15e',
    messagingSenderId: '632269329403',
    projectId: 'flutter-bt-firebase',
    storageBucket: 'flutter-bt-firebase.appspot.com',
    iosClientId: '632269329403-84uub7gjipdvvkuibaim6an3o6q07dec.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcampApp.RunnerTests',
  );
}
